# Generated by Django 3.0.4 on 2020-03-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200)),
                ('reference_id', models.CharField(max_length=200)),
                ('test_case_id', models.CharField(max_length=200)),
                ('data', models.TextField()),
            ],
        ),
    ]
